[project]
name = "routersense-rpi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.119.0",
    "libinspector>=1.0.11",
    "uvicorn>=0.38.0",
]
